// <auto-generated />
using System;
using EducAR.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducAR.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630134608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EducAR.API.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumno"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEscuela")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlumno");

                    b.HasIndex("IdEscuela");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("EducAR.API.Models.AlumnoCurso", b =>
                {
                    b.Property<int>("IdAlumnoCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumnoCurso"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.HasKey("IdAlumnoCurso");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdAlumno", "IdCurso")
                        .IsUnique();

                    b.ToTable("AlumnoCursos");
                });

            modelBuilder.Entity("EducAR.API.Models.AlumnoTutor", b =>
                {
                    b.Property<int>("IdAlumnoTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumnoTutor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsResponsablePrinc")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdTutor")
                        .HasColumnType("int");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlumnoTutor");

                    b.HasIndex("IdTutor");

                    b.HasIndex("IdAlumno", "IdTutor")
                        .IsUnique();

                    b.ToTable("AlumnoTutores");
                });

            modelBuilder.Entity("EducAR.API.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdAlumno", "IdCurso", "Fecha")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("EducAR.API.Models.Boletin", b =>
                {
                    b.Property<int>("IdBoletin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoletin"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoEvaluacion")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBoletin");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdPeriodoEvaluacion");

                    b.ToTable("Boletines");
                });

            modelBuilder.Entity("EducAR.API.Models.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalificacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoEvaluacion")
                        .HasColumnType("int");

                    b.Property<int?>("NivelCalificacion")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorCalificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdPeriodoEvaluacion");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("EducAR.API.Models.CicloLectivo", b =>
                {
                    b.Property<int>("IdCicloLectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCicloLectivo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEscuela")
                        .HasColumnType("int");

                    b.HasKey("IdCicloLectivo");

                    b.HasIndex("IdEscuela");

                    b.ToTable("CiclosLectivos");
                });

            modelBuilder.Entity("EducAR.API.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<int>("IdCicloLectivo")
                        .HasColumnType("int");

                    b.Property<int>("IdEscuela")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdCicloLectivo");

                    b.HasIndex("IdEscuela");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("EducAR.API.Models.DetalleBoletin", b =>
                {
                    b.Property<int>("IdDetalleBoletin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleBoletin"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("BoletinIdBoletin")
                        .HasColumnType("int");

                    b.Property<decimal>("CalificacionFinal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ConceptoFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBoletin")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleBoletin");

                    b.HasIndex("BoletinIdBoletin");

                    b.HasIndex("IdBoletin");

                    b.HasIndex("IdMateria");

                    b.ToTable("DetallesBoletines");
                });

            modelBuilder.Entity("EducAR.API.Models.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdDocente");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("EducAR.API.Models.DocenteMateriaCurso", b =>
                {
                    b.Property<int>("IdDocenteMateriaCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocenteMateriaCurso"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdDocenteMateriaCurso");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdDocente", "IdMateria", "IdCurso")
                        .IsUnique();

                    b.ToTable("DocenteMateriaCursos");
                });

            modelBuilder.Entity("EducAR.API.Models.Escuela", b =>
                {
                    b.Property<int>("IdEscuela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscuela"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEscuela");

                    b.ToTable("Escuelas");
                });

            modelBuilder.Entity("EducAR.API.Models.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEscuela")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdEscuela");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("EducAR.API.Models.Mensaje", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMensaje"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuarioDestinat")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioRemitente")
                        .HasColumnType("int");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("MensajeTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMensaje");

                    b.HasIndex("IdUsuarioDestinat");

                    b.HasIndex("IdUsuarioRemitente");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("EducAR.API.Models.PeriodoEvaluacion", b =>
                {
                    b.Property<int>("IdPeriodoEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodoEvaluacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCicloLectivo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPeriodoEvaluacion");

                    b.HasIndex("IdCicloLectivo");

                    b.ToTable("PeriodosEvaluacion");
                });

            modelBuilder.Entity("EducAR.API.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EducAR.API.Models.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTutor"));

                    b.Property<bool>("EsResponsable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdTutor");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("EducAR.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEscuela")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdEscuela", "NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EducAR.API.Models.Alumno", b =>
                {
                    b.HasOne("EducAR.API.Models.Escuela", "Escuela")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdEscuela")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("EducAR.API.Models.AlumnoCurso", b =>
                {
                    b.HasOne("EducAR.API.Models.Alumno", "Alumno")
                        .WithMany("AlumnoCursos")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Curso", "Curso")
                        .WithMany("AlumnoCursos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EducAR.API.Models.AlumnoTutor", b =>
                {
                    b.HasOne("EducAR.API.Models.Alumno", "Alumno")
                        .WithMany("AlumnoTutores")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Tutor", "Tutor")
                        .WithMany("AlumnoTutores")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("EducAR.API.Models.Asistencia", b =>
                {
                    b.HasOne("EducAR.API.Models.Alumno", "Alumno")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Curso", "Curso")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Docente", "Docente")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("EducAR.API.Models.Boletin", b =>
                {
                    b.HasOne("EducAR.API.Models.Alumno", "Alumno")
                        .WithMany("Boletines")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Curso", "Curso")
                        .WithMany("Boletines")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.PeriodoEvaluacion", "PeriodoEvaluacion")
                        .WithMany("Boletines")
                        .HasForeignKey("IdPeriodoEvaluacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");

                    b.Navigation("PeriodoEvaluacion");
                });

            modelBuilder.Entity("EducAR.API.Models.Calificacion", b =>
                {
                    b.HasOne("EducAR.API.Models.Alumno", "Alumno")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Materia", "Materia")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.PeriodoEvaluacion", "PeriodoEvaluacion")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdPeriodoEvaluacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Materia");

                    b.Navigation("PeriodoEvaluacion");
                });

            modelBuilder.Entity("EducAR.API.Models.CicloLectivo", b =>
                {
                    b.HasOne("EducAR.API.Models.Escuela", "Escuela")
                        .WithMany("CiclosLectivos")
                        .HasForeignKey("IdEscuela")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("EducAR.API.Models.Curso", b =>
                {
                    b.HasOne("EducAR.API.Models.CicloLectivo", "CicloLectivo")
                        .WithMany("Cursos")
                        .HasForeignKey("IdCicloLectivo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Escuela", "Escuela")
                        .WithMany("Cursos")
                        .HasForeignKey("IdEscuela")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CicloLectivo");

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("EducAR.API.Models.DetalleBoletin", b =>
                {
                    b.HasOne("EducAR.API.Models.Boletin", null)
                        .WithMany("DetallesBoletines")
                        .HasForeignKey("BoletinIdBoletin");

                    b.HasOne("EducAR.API.Models.Boletin", "Boletin")
                        .WithMany("Detalles")
                        .HasForeignKey("IdBoletin")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Materia", "Materia")
                        .WithMany("DetallesBoletines")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Boletin");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EducAR.API.Models.Docente", b =>
                {
                    b.HasOne("EducAR.API.Models.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("EducAR.API.Models.Docente", "IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EducAR.API.Models.DocenteMateriaCurso", b =>
                {
                    b.HasOne("EducAR.API.Models.Curso", "Curso")
                        .WithMany("DocenteMateriaCursos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Docente", "Docente")
                        .WithMany("DocenteMateriaCursos")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Materia", "Materia")
                        .WithMany("DocenteMateriaCursos")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EducAR.API.Models.Materia", b =>
                {
                    b.HasOne("EducAR.API.Models.Escuela", "Escuela")
                        .WithMany("Materias")
                        .HasForeignKey("IdEscuela")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("EducAR.API.Models.Mensaje", b =>
                {
                    b.HasOne("EducAR.API.Models.Usuario", "Destinatario")
                        .WithMany("MensajesRecibidos")
                        .HasForeignKey("IdUsuarioDestinat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Usuario", "Remitente")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("IdUsuarioRemitente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("EducAR.API.Models.PeriodoEvaluacion", b =>
                {
                    b.HasOne("EducAR.API.Models.CicloLectivo", "CicloLectivo")
                        .WithMany("PeriodosEvaluacion")
                        .HasForeignKey("IdCicloLectivo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CicloLectivo");
                });

            modelBuilder.Entity("EducAR.API.Models.Tutor", b =>
                {
                    b.HasOne("EducAR.API.Models.Usuario", "Usuario")
                        .WithOne("Tutor")
                        .HasForeignKey("EducAR.API.Models.Tutor", "IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EducAR.API.Models.Usuario", b =>
                {
                    b.HasOne("EducAR.API.Models.Escuela", "Escuela")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEscuela")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducAR.API.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Escuela");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EducAR.API.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoCursos");

                    b.Navigation("AlumnoTutores");

                    b.Navigation("Asistencias");

                    b.Navigation("Boletines");

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("EducAR.API.Models.Boletin", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("DetallesBoletines");
                });

            modelBuilder.Entity("EducAR.API.Models.CicloLectivo", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("PeriodosEvaluacion");
                });

            modelBuilder.Entity("EducAR.API.Models.Curso", b =>
                {
                    b.Navigation("AlumnoCursos");

                    b.Navigation("Asistencias");

                    b.Navigation("Boletines");

                    b.Navigation("DocenteMateriaCursos");
                });

            modelBuilder.Entity("EducAR.API.Models.Docente", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("DocenteMateriaCursos");
                });

            modelBuilder.Entity("EducAR.API.Models.Escuela", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("CiclosLectivos");

                    b.Navigation("Cursos");

                    b.Navigation("Materias");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EducAR.API.Models.Materia", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("DetallesBoletines");

                    b.Navigation("DocenteMateriaCursos");
                });

            modelBuilder.Entity("EducAR.API.Models.PeriodoEvaluacion", b =>
                {
                    b.Navigation("Boletines");

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("EducAR.API.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EducAR.API.Models.Tutor", b =>
                {
                    b.Navigation("AlumnoTutores");
                });

            modelBuilder.Entity("EducAR.API.Models.Usuario", b =>
                {
                    b.Navigation("Docente");

                    b.Navigation("MensajesEnviados");

                    b.Navigation("MensajesRecibidos");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
